In [1]:
import numpy as np

def normalization(A):
    mean = np.mean(A)
    std = np.std(A)
    ans = ( A - mean ) / std
    
    return ans

In [3]:
rand = np.random.randint(1, 100, size = (5, 5))
print(rand)
print(normalization(rand))

[[49 10 96 19 63]
 [89 44 26 48 72]
 [93 52 83 53 84]
 [50 98 34 86 19]
 [43 62 66 99 99]]
[[-0.4606673  -1.9002526   1.27421756 -1.56804061  0.05610691]
 [ 1.01583045 -0.64522952 -1.3096535  -0.49757974  0.38831891]
 [ 1.16348023 -0.34992997  0.79435579 -0.31301752  0.83126823]
 [-0.42375485  1.34804245 -1.01435395  0.90509312 -1.56804061]
 [-0.68214196  0.01919447  0.16684425  1.38495489  1.38495489]]
