In [7]:
import numpy as np
A = np.random.randint(1,10,(5, 3))
B = np.random.randint(1, 10, (3, 2))
print("A=")
print(A)
print("B=")
print(B)
print("AB=")
print(np.dot(A, B))

A=
[[4 3 6]
 [4 3 7]
 [8 3 8]
 [2 5 5]
 [8 9 8]]
B=
[[1 7]
 [3 8]
 [2 4]]
A B=
[[ 25  76]
 [ 27  80]
 [ 33 112]
 [ 27  74]
 [ 51 160]]
