In [3]:
#Q1:FizzBuzz

for i in range(1,101):
    if(i%15 == 0):
        print('FizzBuzz')
    elif(i%3 == 0):
        print('Fizz')
    elif(i%5 == 0):
        print('Buzz')
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [24]:
#Q2:Quick Sort
def swap (A, a, b):
    temp = A[a]
    A[a] = A[b]
    A[b] = temp

def partition(A, p, r):
    for i in range(p, r):
        if(A[i] <= A[r]):
            swap(A, p, i)
            p += 1
    swap(A, r, p)
    return p

def QuickSort(A, p, n):
    if(p < n):
        x = partition(A, p, n)
        QuickSort(A, p, x-1)
        QuickSort(A, x, n)
        
A = [9,8,7,5,6,3,1,2,4]

QuickSort(A, 0, len(A)-1)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
#Q3:Miising Element
def swap (A, a, b):
    temp = A[a]
    A[a] = A[b]
    A[b] = temp

def partition(A, p, r):
    for i in range(p, r):
        if(A[i] <= A[r]):
            swap(A, p, i)
            p += 1
    swap(A, r, p)
    return p

def QuickSort(A, p, n):
    if(p < n):
        x = partition(A, p, n)
        QuickSort(A, p, x-1)
        QuickSort(A, x, n)
        
def SearchMissing(A, B):
    QuickSort(A, 0, len(A)-1)
    QuickSort(B, 0, len(B)-1)
    
    if (len(A) < len(B)):
        for i in range(len(A)):
            if(A[i] != B[i]):
                print(B[i])
                break
            if(i == len(A)-1):
                print(B[len(A)])
    else:
        for i in range(len(B)):
            if(A[i] != B[i]):
                print(A[i])
                break
            if(i == len(B)-1):
                print(A[len(B)])
                
A = [2,3,4,5,6,7,5,8]
B = [6,8,7,4,5,2,3]

SearchMissing(A, B)


5


In [39]:
#Q4:Pair Sum
def PairSum(A, k):
    r = len(A)-1
    for i in range(r):
        for j in range(i, r):
            if(A[i] + A[j] == k):
                print('(',A[i],',',A[j],')', sep='')
                
A = [1,3,2,2]
k = 4

PairSum(A, k)

(1,3)
(2,2)


In [51]:
#Q5:Multiplication Table

print('1  |', end='')
for i in range(1,11):
    print(str(i).rjust(4), end='')
print()
for i in range(44):
    print('#', end='')
print()
    
for i in range(1,11):
    print(str(i).ljust(2), '|', end='')
    for j in range(1,11):
        print(str(i*j).rjust(4), end='')
    print()

1  |   1   2   3   4   5   6   7   8   9  10
############################################
1  |   1   2   3   4   5   6   7   8   9  10
2  |   2   4   6   8  10  12  14  16  18  20
3  |   3   6   9  12  15  18  21  24  27  30
4  |   4   8  12  16  20  24  28  32  36  40
5  |   5  10  15  20  25  30  35  40  45  50
6  |   6  12  18  24  30  36  42  48  54  60
7  |   7  14  21  28  35  42  49  56  63  70
8  |   8  16  24  32  40  48  56  64  72  80
9  |   9  18  27  36  45  54  63  72  81  90
10 |  10  20  30  40  50  60  70  80  90 100


In [53]:
#Q6
import numpy as np

a = np.array([[0,1],[1,0]])
a_check = np.tile(a,(4,4))
print(a_check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [67]:
#Q7
import numpy as np
#0～100の整数で5×5の行列を作る
a = np.random.randint(0,100,(5,5))
print(a)

max = np.max(a)
min = np.min(a)
#round(a,n)配列aを小数点第4位で四捨五入
result = np.round((a-min)/(max-min), decimals=4)
print(result)

[[65 33 79 78 75]
 [55 15 51 75 93]
 [15 80 15 77  7]
 [97 23 50 14 14]
 [28 45 83 46 95]]
[[0.6444 0.2889 0.8    0.7889 0.7556]
 [0.5333 0.0889 0.4889 0.7556 0.9556]
 [0.0889 0.8111 0.0889 0.7778 0.    ]
 [1.     0.1778 0.4778 0.0778 0.0778]
 [0.2333 0.4222 0.8444 0.4333 0.9778]]


In [75]:
#Q8
import numpy as np

left = np.random.rand(5,3)
right = np.random.rand(3,2)
print(left)
print(right)

print('Result')
print(np.dot(left, right))

[[0.888587   0.19374731 0.67310523]
 [0.96140464 0.4865382  0.46584298]
 [0.3733971  0.91118088 0.37559433]
 [0.39757376 0.49071912 0.46467057]
 [0.07582855 0.87411225 0.4908582 ]]
[[0.05030441 0.70798499]
 [0.08560156 0.38402442]
 [0.87458092 0.68470663]]
Result
[[0.64996991 1.16438958]
 [0.49742871 1.18646839]
 [0.42526966 0.87144718]
 [0.46839805 0.78808741]
 [0.5079351  0.72545979]]


In [3]:
#Q9
import numpy as np

a = np.random.randint(0,10,10)
print(a)

i=0
while(1):
    if a[i] >= 3 and a[i] <= 8:
        a = np.delete(a, i)
    else:
        i += 1
    if(i == np.size(a)):
        break

print(a)

[8 1 9 8 4 2 4 4 0 9]
[1 9 2 0 9]


In [28]:
#Q10
import numpy as np

#A = np.random.randint(0,10,2)
#B = np.random.randint(0,10,2)

A = np.array([0,1,5])
B = np.array([0,1,5])


flag = 1
L = np.size(A)
for i in range(L):
    if(A[i] != B[i]):
        flag = 0
        break
    i += 1

print('A',A)
print('B',B)

if(flag == 1):
    print('A and B are equal')
else:
    print('A and B are NOT equal')

A [0 1 5]
B [0 1 5]
A and B are equal
