In [1]:
import numpy as np

Arr= np.arange(16).reshape(4, 4)
kernel = np.random.randint(1, 5, (2, 2))
bias = [1]

print("Arr:",Arr)
print("kernel:",kernel)

size, _ = Arr.shape
k_size, _ =  kernel.shape

ans = np.zeros((size-(k_size-1), size-(k_size-1)), dtype = int)

for i in range(size-(k_size-1)):
    for j in range(size-(k_size-1)):
        tmpArr = Arr[i:(i+k_size), j:(j+k_size)]
        tmp = np.sum(tmpArr*kernel)
        ans[i,j] = tmp
        
ans += bias

print(ans)

Arr: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
kernel: [[4 3]
 [2 4]]
[[ 32  45  58]
 [ 84  97 110]
 [136 149 162]]
