In [9]:
#createcheckboard
import numpy as np

a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)
b = np.tile( np.array([['a'],['b']]), (3, 3))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[['a' 'a' 'a']
 ['b' 'b' 'b']
 ['a' 'a' 'a']
 ['b' 'b' 'b']
 ['a' 'a' 'a']
 ['b' 'b' 'b']]
