In [4]:
#dotarray
import numpy as np

a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
print(a)
print(b)
print(np.dot(a, b))

[[0.19892549 0.99131865 0.11668387]
 [0.58631254 0.66789454 0.34573639]
 [0.66641054 0.3118739  0.98127169]
 [0.96138284 0.47152306 0.80619358]
 [0.60059726 0.16674684 0.3928267 ]]
[[0.534121   0.73675479]
 [0.94041435 0.01343358]
 [0.14991865 0.40652399]]
[[1.05599365 0.20731106]
 [0.99309179 0.58149093]
 [0.79634549 0.89408123]
 [1.07778527 1.04237469]
 [0.53649478 0.60442639]]
