In [1]:
import numpy as np

In [7]:
#Q1:FizzBuss

for i in range(1, 101):
    if i%3 == 0 and i%5 == 0:
        print('FizzBuzz')
    elif i%3 == 0:
        print('Fizz')
    elif i%5 == 0:
        print('Buzz')
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [2]:
def quicksort(input):
    l, r, output = [],[],[]
    p = input[0]
    for i in range(1,len(input)):
        if input[i] >= p:
            r.append(input[i])
        else:
            l.append(input[i])
            
    if len(r) > 1:
        r = quicksort(r)
    if len(l) > 1:
        l = quicksort(l)

    output.extend(l)
    output.append(p)
    output.extend(r)

    return output


In [3]:
#Q2:Quick Sort

x = [9,8,7,5,6,3,1,2,4]
print(x)
x_sort = quicksort(x)
print(x_sort)


[9, 8, 7, 5, 6, 3, 1, 2, 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
#Q3:Missing Element
a = [2, 3, 4, 5, 6, 7, 5, 8]
b = [6, 8, 7, 4, 5, 2, 3]

a = quicksort(a)
b = quicksort(b)

missing = []
j = 0
for i in range(len(a)):
    if i < len(b):
        if a[i] == b[j]:
            j = j + 1
        else:
            missing = a[i]
print(missing)


5


In [11]:
#Q4:Pair Sum
input = [1,3,2,2]
k = 4

pair = []
for i in range(len(input)-1):
    for j in range(i+1,len(input)):
        if input[i] + input[j] == k:
            pair.append([input[i],input[j]])
print(pair)


[[1, 3], [2, 2]]


In [6]:
#Q5:Multiplication Table
x = list(range(1,11))

for i in range(len(x)):
    y = x[i]
    print('%3d |' % (y), end='')
    for j in range(len(x)):
        print(' %3d' % (x[j]*y), end='')
    print('')
    if i == 0:
        print('#############################################')




  1 |   1   2   3   4   5   6   7   8   9  10
#############################################
  2 |   2   4   6   8  10  12  14  16  18  20
  3 |   3   6   9  12  15  18  21  24  27  30
  4 |   4   8  12  16  20  24  28  32  36  40
  5 |   5  10  15  20  25  30  35  40  45  50
  6 |   6  12  18  24  30  36  42  48  54  60
  7 |   7  14  21  28  35  42  49  56  63  70
  8 |   8  16  24  32  40  48  56  64  72  80
  9 |   9  18  27  36  45  54  63  72  81  90
 10 |  10  20  30  40  50  60  70  80  90 100


In [13]:
#Q6
a = np.array([[0,1]])

checker = np.tile(np.concatenate([a,np.fliplr(a)],0),(4,4))

print(checker)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#Q7
matrix = np.random.randint(25,size=(5,5))
print(matrix)

m_mean = matrix.mean(axis=None, keepdims=True)
m_std = np.std(matrix, axis=None, keepdims=True)
norm_matrix = (matrix-m_mean)/m_std

print(norm_matrix)

[[24 22 12 13 20]
 [ 0 18 17 21 14]
 [22  6 24 10  4]
 [ 3  2 10 21  6]
 [ 4  4 15 10  1]]
[[ 1.52829065  1.27100266 -0.01543728  0.11320671  1.01371467]
 [-1.5591652   0.75642668  0.62778269  1.14235866  0.24185071]
 [ 1.27100266 -0.78730124  1.52829065 -0.27272527 -1.04458923]
 [-1.17323322 -1.30187722 -0.27272527  1.14235866 -0.78730124]
 [-1.04458923 -1.04458923  0.3704947  -0.27272527 -1.43052121]]


In [25]:
#Q8
a = np.array([[1,2,3,],
              [4,5,6],
              [7,8,9],
              [10,11,12],
              [13,14,15]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [6]:
#Q9
x = np.random.rand(10)*10
print(x)

y = []
for i in range(len(x)):
    if x[i] < 3 or x[i] > 8:
        y.append(x[i])
print(np.array(y))


[3.9236141  9.47116419 4.23935341 7.36461614 9.8741341  8.83649303
 8.03222922 2.50120237 6.94189664 9.95183583]
[9.47116419 9.8741341  8.83649303 8.03222922 2.50120237 9.95183583]


In [44]:
#Q10
def compare(a,b):
    y = False
    if len(a) == len(b):
        for i in range(len(a)):
            if a[i] != b[i]:
                break
            elif i == len(a)-1:
                y = True
    return y


a = np.random.randint(0,2,3)
b = np.random.randint(0,2,3)

print(a,b)

if compare(a,b):
    print('Equal.')
else:
    print('Not equal.')

[1 1 0] [1 1 1]
Not equal.
